Edit-readme
ide-ryunosuke/chat-space pull request #1
Opened 2019-02-11 12:26 UTC by ide-ryunosuke

# WHAT
READMEにデータベース設計を記述

#WHY
データベース設計を文書をして表示する為

2019-02-11 12:56 UTC, yuki-uchida requested changes

2019-02-11 12:56 UTC, yuki-uchida commented on README.md
> +|user_id|integer|null :false, foreign_key :true|
外部テーブルの場合は、integerではなくrefferenceとしましょう！

2019-02-11 12:56 UTC, yuki-uchida commented on README.md
> +|user_id|integer|null :false, foreign_key :true|
こちらも

2019-02-12 04:34 UTC, ide-ryunosuke commented on README.md
> +|user_id|integer|null :false, foreign_key :true|
修正しました

2019-02-12 04:34 UTC, ide-ryunosuke commented on README.md
> +|user_id|integer|null :false, foreign_key :true|
修正しました

2019-02-12 04:38 UTC, hzak2xx approved these changes
LGTM

2019-02-12 04:50 UTC, merged